server.port: 9090
serverTimezone: Europe/France
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 5 #in Hours

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stream?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
   # url: jdbc:mysql://streamlinkdatabasefinal.mysql.database.azure.com:3306/streamlink?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#    username: streamadmin@streamlinkdatabasefinal
#    password: Temporaire99ABC
    username: root
    password: root
  jpa:
    database: MYSQL
    show_sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        cache.use_query_cache: false
        generate_statistics: false
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    rest.base-path: api
  #    web.pageable.one-indexed-parameters: true

  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 10MB

contact:
  hireability:
    url: http://processing.resumeparser.com/requestprocessing.html
    product_code: e11adbba5cffb9a8b529097145a2a86f
  security:
    token:
debug: true
