#contact:
#  security:
#    token:
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://streamlinkdatabasefinal.mysql.database.azure.com:3306/stream?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
        username: streamadmin@streamlinkdatabasefinal
        password: Temporaire99ABC
    jpa:
        database: MYSQL
        show_sql: false
        hibernate:
            ddl-auto: update

contact:
    avatar:
        path: /destination/files/avatars

    cv:
        path: /destination/files/cvs
