spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  #  datasource:
  #    url: jdbc:h2:file:~/developer
  #    username: test
  #    password:
  #    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/contact?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    name: contact
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      pool-name: contact_pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  application:
    name: service-streamlink

contact:
  security:
    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJhdXRoIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJpYXQiOjE1MzMxMzg3MzIsImV4cCI6MTUzNjczODczMn0.AiXci7rjitucF9gyd8Rel-eV9p3hrIOVd54j0Z8OW8Q
  cv:
    path: C:\ldk\cv\
    url: http://localhost:8000/
  gate:
    home: C:\ldk\workspace\streamlink_condidats_manager\src\main\resources\GATEFiles
    plugins: C:\ldk\workspace\streamlink_condidats_manager\src\main\resources\GATEFiles\plugins
  hireability:
    path: C:\ldk\cv\hireability